# ppe_openvino_pipeline.py
"""
PPE detection pipeline using:
- Ultralytics YOLO (.pt) exported to OpenVINO
- OpenVINO Runtime for inference on Intel devices (GPU or CPU)
- Multithreaded: capture -> inference -> display
"""

import os
import time
import cv2
import threading
from queue import Queue, Empty
from datetime import datetime
from dotenv import load_dotenv

# Ultralytics for export convenience (we'll use OpenVINO runtime for inference)
from ultralytics import YOLO

# OpenVINO Runtime (new API)
try:
    from openvino.runtime import Core
except Exception as e:
    raise RuntimeError("OpenVINO runtime not found. Install 'openvino' package.") from e

load_dotenv()

# -----------------------
# CONFIG
# -----------------------
MODEL_PT_PATH = os.getenv("MODEL_PATH", "../models/ppe_model_v1/ppe_best_model_10epoch.pt")
# Optional: if you already exported, point to the exported folder or xml
OPENVINO_MODEL_DIR = os.getenv("OPENVINO_MODEL_DIR", "")  # if empty, script will call export()
CAMERA_SOURCE = os.getenv("CCTV_URL", "0")  # '0' for webcam or 'rtsp://...'
VIOLATION_CLASSES = ['no_helmet', 'no_glove', 'no_goggles', 'no_mask', 'no_shoes']

# Performance / pipeline tuning
INFERENCE_WIDTH = int(os.getenv("INFERENCE_WIDTH", "640"))
MAX_QUEUE_SIZE = int(os.getenv("MAX_QUEUE_SIZE", "2"))
CONFIDENCE_THRESHOLD = float(os.getenv("CONFIDENCE_THRESHOLD", "0.5"))
SCREENSHOT_COOLDOWN = int(os.getenv("SCREENSHOT_COOLDOWN", "5"))
MIN_VIOLATION_DURATION = float(os.getenv("MIN_VIOLATION_DURATION", "1.0"))

VIOLATIONS_FOLDER = os.getenv("VIOLATIONS_FOLDER", "../PPE-DETECTION/violations")
os.makedirs(VIOLATIONS_FOLDER, exist_ok=True)

# -----------------------
# STEP A: Ensure OpenVINO model exists (export if needed)
# -----------------------
def export_to_openvino_if_needed(pt_path, out_dir_hint="openvino_model"):
    """
    If OPENVINO_MODEL_DIR not provided, export using Ultralytics: model.export(format='openvino')
    Returns path to directory that contains the .xml file.
    """
    # If user provided OPENVINO_MODEL_DIR via env, honor it
    if OPENVINO_MODEL_DIR:
        ov_dir = OPENVINO_MODEL_DIR
        # check for xml inside
        for f in os.listdir(ov_dir):
            if f.endswith(".xml"):
                return ov_dir
        print("[!] Given OPENVINO_MODEL_DIR doesn't contain .xml - will try export anyway.")
    # Export using ultralytics
    print("Exporting .pt -> OpenVINO format (this may take a while)...")
    model = YOLO(pt_path)
    ov_path = model.export(format="openvino")
    print("Export done. OpenVINO model at:", ov_path)
    return ov_path

# -----------------------
# STEP B: Load compiled model with OpenVINO Runtime
# -----------------------
def load_openvino_model(ov_model_dir, device_preference="GPU"):
    """
    ov_model_dir: folder generated by ultralytics export with an .xml file
    device_preference: "GPU" for Intel iGPU, fallback "CPU"
    """
    core = Core()
    # find xml file
    xml_path = None
    for f in os.listdir(ov_model_dir):
        if f.endswith(".xml"):
            xml_path = os.path.join(ov_model_dir, f)
            break
    if xml_path is None:
        raise FileNotFoundError("OpenVINO .xml not found in " + ov_model_dir)

    # Try compile on preferred device, fallback to CPU
    try:
        print(f"Compiling model for device: {device_preference} ...")
        compiled = core.compile_model(model=xml_path, device_name=device_preference)
        print("Compiled for", device_preference)
        return core, compiled, device_preference
    except Exception as e:
        print(f"Failed to compile on {device_preference}: {e}. Falling back to CPU.")
        compiled = core.compile_model(model=xml_path, device_name="CPU")
        return core, compiled, "CPU"

# -----------------------
# STEP C: Utility helpers
# -----------------------
def parse_camera_source(src):
    if src.lower() in ("webcam", "0"):
        return 0
    if str(src).isdigit():
        return int(src)
    return src

def resize_frame(frame, max_width=1280, max_height=720):
    h, w = frame.shape[:2]
    scale_w = max_width / w
    scale_h = max_height / h
    scale = min(scale_w, scale_h, 1.0)
    if scale < 1.0:
        return cv2.resize(frame, (int(w*scale), int(h*scale)), interpolation=cv2.INTER_AREA), scale
    return frame, 1.0

# Violation tracker from previous script
class ViolationTracker:
    def __init__(self):
        self.last_screenshot_time = {}
        self.violation_start_time = {}
        self.current_violations = set()
        self.total_screenshots = 0
    def update_violations(self, detected_violations):
        current_set = set(detected_violations)
        new = current_set - self.current_violations
        resolved = self.current_violations - current_set
        now = time.time()
        for v in new:
            self.violation_start_time[v] = now
        for v in resolved:
            self.violation_start_time.pop(v, None)
            self.last_screenshot_time.pop(v, None)
        self.current_violations = current_set
        return new, resolved
    def should_screenshot(self, violation_type, current_time):
        if violation_type in self.violation_start_time:
            if current_time - self.violation_start_time[violation_type] < MIN_VIOLATION_DURATION:
                return False, "duration_too_short"
        if violation_type in self.last_screenshot_time:
            if current_time - self.last_screenshot_time[violation_type] < SCREENSHOT_COOLDOWN:
                return False, "cooldown"
        return True, "ok"
    def record_screenshot(self, v):
        self.last_screenshot_time[v] = time.time()
        self.total_screenshots += 1

tracker = ViolationTracker()

# -----------------------
# STEP D: Pipeline threads (capture & openvino inference)
# -----------------------
frames_q = Queue(maxsize=MAX_QUEUE_SIZE)
out_q = Queue(maxsize=MAX_QUEUE_SIZE)
stop_event = threading.Event()

def grab_thread(cap, q, stop_event):
    """Continuously read frames."""
    while not stop_event.is_set():
        ret, frame = cap.read()
        if not ret:
            time.sleep(0.5)
            continue
        try:
            q.put_nowait(frame)
        except:
            try:
                _ = q.get_nowait()
                q.put_nowait(frame)
            except:
                pass

def openvino_inference_worker(frames_q, out_q, stop_event, core, compiled_model, device_name, input_shape=None):
    """
    frames_q -> read BGR OpenCV frames (H,W,3)
    Preprocess to match model's expected input:
      - resize to INFERENCE_WIDTH while maintaining aspect ratio
      - convert BGR->RGB, transpose HWC->CHW, expand dims, cast to float32 and normalize (0..1)
    Use compiled_model to create an inference request and infer synchronously.
    Returns: original_frame, scale_used, list_of_boxes (xyxy on inf_frame scale), class_id, conf
    """
    # determine input name and shape
    input_port = compiled_model.inputs[0]
    input_name = input_port.any_name
    # get expected height/width from model input if available
    # Some OpenVINO models have dynamic shapes - we will size according to our INFERENCE_WIDTH.
    while not stop_event.is_set():
        try:
            frame = frames_q.get(timeout=0.5)
        except Empty:
            continue
        h, w = frame.shape[:2]
        scale = 1.0
        inf_frame = frame
        if w > INFERENCE_WIDTH:
            scale = INFERENCE_WIDTH / float(w)
            new_w = INFERENCE_WIDTH
            new_h = int(h * scale)
            inf_frame = cv2.resize(frame, (new_w, new_h), interpolation=cv2.INTER_LINEAR)

        # Preprocess: BGR -> RGB, HWC->CHW, float32, /255
        img = cv2.cvtColor(inf_frame, cv2.COLOR_BGR2RGB)
        img = img.astype('float32') / 255.0
        # transpose to CHW
        img = img.transpose(2, 0, 1)  # C, H, W
        # add batch dim
        inp = img.reshape(1, *img.shape)

        # Run inference
        try:
            # create infer request and run
            infer_result = compiled_model.infer_new_request({input_name: inp})
        except AttributeError:
            # fallback: older API
            req = compiled_model.create_infer_request()
            req.infer({input_name: inp})
            infer_result = req.get_output_tensor(0).data  # this may vary; we'll parse differently below

        # Parse outputs: Ultralytics-exported OpenVINO model usually outputs detections in a known tensor shape.
        # We'll attempt to locate output tensor(s) automatically and parse boxes (xyxy), conf, class.
        # NOTE: output format might vary by export version. Here we attempt a general parsing strategy.
        boxes = []
        # generic approach: iterate outputs, look for shape NxM where M >= 6 (x,y,w,h,conf,cls)
        for out in compiled_model.outputs:
            out_name = out.get_any_name()
            # get numpy array from infer_result
            try:
                res = infer_result[out_name]
            except Exception:
                try:
                    res = infer_result  # fallback
                except Exception:
                    res = None
            if res is None:
                continue
            import numpy as np
            arr = np.array(res)
            if arr.ndim == 3 and arr.shape[-1] >= 6:
                # assume format [N, num_dets, 6+] with (x,y,w,h,score, class) or (x1,y1,x2,y2,score, class)
                N, M, K = arr.shape
                # iterate detections
                for i in range(N):
                    for j in range(M):
                        det = arr[i, j]  # vector
                        conf = float(det[4])
                        if conf < CONFIDENCE_THRESHOLD:
                            continue
                        cls_id = int(det[5])
                        x1, y1, x2, y2 = None, None, None, None
                        # if format is xywh
                        if K >= 6:
                            # some exports use cx,cy,w,h -> convert to xyxy
                            cx, cy, bw, bh = float(det[0]), float(det[1]), float(det[2]), float(det[3])
                            x1 = cx - bw/2.0
                            y1 = cy - bh/2.0
                            x2 = cx + bw/2.0
                            y2 = cy + bh/2.0
                        else:
                            continue
                        boxes.append(([x1, y1, x2, y2], cls_id, conf))
                break
            # if arr is 2D and columns >=6 treat similarly
            if arr.ndim == 2 and arr.shape[1] >= 6:
                for row in arr:
                    conf = float(row[4])
                    if conf < CONFIDENCE_THRESHOLD:
                        continue
                    cls_id = int(row[5])
                    cx, cy, bw, bh = float(row[0]), float(row[1]), float(row[2]), float(row[3])
                    x1 = cx - bw/2.0
                    y1 = cy - bh/2.0
                    x2 = cx + bw/2.0
                    y2 = cy + bh/2.0
                    boxes.append(([x1, y1, x2, y2], cls_id, conf))
                break

        # push result (original frame, scale, boxes)
        try:
            out_q.put_nowait((frame, scale, boxes))
        except:
            try:
                _ = out_q.get_nowait()
                out_q.put_nowait((frame, scale, boxes))
            except:
                pass

# -----------------------
# STEP E: Start pipeline & UI loop
# -----------------------
def main():
    # 1) Ensure OpenVINO model exists
    ov_dir = export_to_openvino_if_needed(MODEL_PT_PATH)

    # 2) load & compile model
    core, compiled_model, device = load_openvino_model(ov_dir, device_preference="GPU")
    print("Using device:", device)

    # open camera
    cap_src = parse_camera_source(CAMERA_SOURCE)
    cap = cv2.VideoCapture(cap_src)
    if isinstance(cap_src, str) and cap_src.startswith("rtsp"):
        cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)
    if not cap.isOpened():
        raise RuntimeError("Cannot open camera source: " + str(cap_src))

    # start threads
    t_g = threading.Thread(target=grab_thread, args=(cap, frames_q, stop_event), daemon=True)
    t_i = threading.Thread(target=openvino_inference_worker, args=(frames_q, out_q, stop_event, core, compiled_model, device), daemon=True)
    t_g.start()
    t_i.start()

    # display loop
    cv2.namedWindow("PPE - OpenVINO", cv2.WINDOW_NORMAL)
    prev = time.time()
    fps_smooth = 0.0
    alpha = 0.3
    # get names mapping from the original PT model for human-readable class names
    # We'll load the pt model for names only (no heavy usage)
    pt_model = YOLO(MODEL_PT_PATH)
    names = list(pt_model.names.values())

    try:
        while True:
            try:
                frame_orig, scale, boxes = out_q.get(timeout=1.0)
            except Empty:
                key = cv2.waitKey(1) & 0xFF
                if key == ord('q'):
                    break
                continue

            now = time.time()
            inst_fps = 1.0 / (now - prev) if now != prev else 0.0
            prev = now
            fps_smooth = (1 - alpha) * fps_smooth + alpha * inst_fps

            display = frame_orig.copy()
            current_dets = {}
            detected_violations = []

            # boxes extracted are in inf_frame coordinates (cx,cy,w,h converted to xyxy)
            for xyxy, cls_id, conf in boxes:
                # scale back if scaling was applied
                if scale != 1.0:
                    x1 = int(xyxy[0] / scale)
                    y1 = int(xyxy[1] / scale)
                    x2 = int(xyxy[2] / scale)
                    y2 = int(xyxy[3] / scale)
                else:
                    x1, y1, x2, y2 = map(int, xyxy)

                class_name = names[cls_id] if cls_id < len(names) else str(cls_id)
                current_dets[class_name] = current_dets.get(class_name, 0) + 1

                if class_name in VIOLATION_CLASSES:
                    detected_violations.append(class_name)
                    cv2.rectangle(display, (x1, y1), (x2, y2), (0,0,255), 2)
                    cv2.putText(display, f"{class_name} {conf:.2f}", (x1, max(20, y1-6)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,0,255), 2)
                else:
                    cv2.rectangle(display, (x1, y1), (x2, y2), (0,255,0), 1)

            # update tracker & screenshots
            new, resolved = tracker.update_violations(detected_violations)
            if new: print("New violations:", new)
            if resolved: print("Resolved:", resolved)

            # screenshot logic
            for v in tracker.current_violations:
                ok, reason = tracker.should_screenshot(v, now)
                if ok:
                    ts = datetime.now().strftime("%Y%m%d_%H%M%S_%f")[:-3]
                    fname = os.path.join(VIOLATIONS_FOLDER, f"violation_{v}_{ts}.jpg")
                    cv2.imwrite(fname, display)
                    tracker.record_screenshot(v)
                    print("Saved screenshot:", fname)

            # HUD
            cv2.rectangle(display, (0,0), (display.shape[1], 70), (0,0,0), -1)
            cv2.putText(display, f"FPS: {int(fps_smooth)}", (10,30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,255,0), 2)
            det_text = " | ".join([f"{k}:{v}" for k,v in current_dets.items()])
            if det_text:
                cv2.putText(display, det_text, (10,55), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,255,255), 1)

            disp_s, _ = resize_frame(display)
            cv2.imshow("PPE - OpenVINO", disp_s)

            key = cv2.waitKey(1) & 0xFF
            if key == ord('q'): break
            elif key == ord('s'):
                fn = os.path.join(VIOLATIONS_FOLDER, f"manual_{datetime.now().strftime('%Y%m%d_%H%M%S')}.jpg")
                cv2.imwrite(fn, display)
                print("Manual screenshot saved:", fn)

    except KeyboardInterrupt:
        print("Interrupted by user.")
    finally:
        stop_event.set()
        t_g.join(timeout=1.0)
        t_i.join(timeout=1.0)
        cap.release()
        cv2.destroyAllWindows()
        print("Done. Screenshots:", VIOLATIONS_FOLDER)

if __name__ == "__main__":
    main()
